#!/bin/bash

set -e

homebrew_packages="$(cat brew_pkgs | xargs)"
apt_packages="$(cat apt_pkgs | xargs)"
os="$(uname -s | tr -d '\n')"

is_installed () {
  # This works with scripts and programs. For more info, check
  # http://goo.gl/B9683D
  type $1 &> /dev/null 2>&1
}

is_brew_installed () {
  brew --prefix "$1" &> /dev/null
}

installed=""
is_apt_installed() {
  [[ -z $installed ]] && installed="$(apt list --installed)"
  echo $installed | grep -q "$1"
}

install_homebrew () {
  if ! is_installed brew; then
    step "Installing Homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi
}

install_homebrew_packages () {
  step "Installing missing packages: $homebrew_packages"
  for package in $homebrew_packages; do
    if ! is_brew_installed $package; then
      echo "Installing $package"
      brew install $package
    fi
  done
}

install_apt_packages () {
  step "Installing missing packages: $apt_packages"
  for package in $apt_packages; do
    if ! is_apt_installed $package; then
      echo "Installing $package"
      sudo apt-get install -y $package
    fi
  done
}

install_nvim_dependencies() {
  if ! ls -A "$HOME/.config/nvim/plugged" &> /dev/null; then
    step "Installing nvim dependencies"

    sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    nvim --headless +PlugInstall +qall
  fi
}

step() {
  cat <<-EOF 1>&2
	==============================
	$1
	------------------------------
	EOF
}

install_pure_prompt () {
  step "Installing pure"
  mkdir -p "$HOME/.zsh"
  git clone https://github.com/sindresorhus/pure.git "$HOME/.zsh/pure"
}

main () {
  local dot_files="${@:-.*}"
  local current_dir
  current_dir="$(pwd)"

  if [[ $# -eq 0 ]]; then
    if [[ $os = "Darwin" ]]; then
      install_homebrew
      install_homebrew_packages
    fi

    if [[ $SPIN ]]; then
      # add neovim 6 apt-repo
      sudo apt purge neovim
      sudo add-apt-repository -y ppa:neovim-ppa/unstable
      sudo apt update

      install_apt_packages
      rm -rf $HOME/.config
      rm -f $HOME/.zshrc
      rm -f $HOME/.gitconfig
      mkdir $HOME/.config
    fi
  fi
}

main "$@"

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" $@

install_pure_prompt
install_nvim_dependencies

